import { chromium } from 'playwright';
const b = await chromium.launch();
let fails = 0; const ok = (c, m) => { console.log(c ? 'ok  ' : 'FAIL', m); if (!c) fails++; };
const p = await (await b.newContext({ locale: 'sv-SE', viewport: { width: 1280, height: 800 } })).newPage();
await p.goto('http://localhost:4173/'); await p.waitForSelector('.badge');
const count = async () => Number(((await p.locator('body').innerText()).match(/(\d+) av \d+ linjer/) ?? [])[1] ?? -1);
await p.click('button.tool:has-text("Filter")');
const chip = (name) => p.locator(`.filter-panel .chip:text-is("${name}")`);
ok((await p.locator('.filter-panel [aria-label="Kategori"] .chip:text-is("Alla")').count()) === 0, 'category group has no "Alla"');
const base = await count();
ok(base > 0, `default shows stadsbuss (${base})`);
await chip('Expressbuss').click();
const withExpress = await count();
ok(withExpress > base, `adding express adds lines (${base} -> ${withExpress})`);
await chip('Industribuss').click();
ok((await count()) > withExpress, 'adding industrial adds more lines');
await chip('Stadsbuss').click();
await chip('Expressbuss').click();
ok((await chip('Industribuss').getAttribute('aria-pressed')) === 'true', 'one category left');
await chip('Industribuss').click();
ok((await chip('Industribuss').getAttribute('aria-pressed')) === 'true', 'last selected category cannot be removed');
await p.mouse.click(700, 400);
await p.waitForTimeout(200);
ok((await p.locator('.filter-panel').count()) === 0, 'clicking the map closes the filter panel');
await b.close(); process.exit(fails);
